version: '3'
services:

  database:
    image: exo7_db:latest
    container_name: exo7_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=doc
      - POSTGRES_USER=doc
      - POSTGRES_PASSWORD=doc

  app:
    build: ./back
    container_name: exo7_back
    environment:
      - DB_HOST=postgres
      - DB_USER=doc
      - DB_PASSWORD=doc
      - DB_NAME=doc
      - DB_PORT=5432
    ports:
      - 4000:4000
    depends_on:
      - database
    # restart: unless-stopped

  front:
    build: ./front
    container_name: exo7_front
    ports:
      - 80:80
    links:
      - app

networks:
  default:
    external:
      name: exo7_network